I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/outside.rpy", line 25, in script
    jump testimony
ScriptError: could not find label 'testimony'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/outside.rpy", line 25, in script
    jump testimony
  File "renpy/ast.py", line 1702, in execute
    rv = renpy.game.script.lookup(target)
  File "renpy/script.py", line 900, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'testimony'.

